# Generated by Django 4.2 on 2023-05-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'managed': False},
        ),
    ]
